stage_1:
  # first round of fine tuning (only the last layers)
  _target_: tensorflow.keras.optimizers.schedules.CosineDecay
  initial_learning_rate: 1e-3
  decay_steps: 100_000

# when finetuning the whole (pretrained) model
stage_2:
  _target_: tensorflow.keras.optimizers.schedules.CosineDecay
  initial_learning_rate: 1e-5
  decay_steps: 100_000
