stage_1:
  # first round of fine tuning (only the last layers)
  _target_: tensorflow.keras.optimizers.schedules.ExponentialDecay
  initial_learning_rate: 4e-3
  decay_steps: 100_000
  decay_rate: 0.96

# when finetuning the whole (pretrained) model
stage_2:
  _target_: tensorflow.keras.optimizers.schedules.ExponentialDecay
  initial_learning_rate: 5e-5
  decay_steps: 100_000
  decay_rate: 0.99
