architecture: ConvNeXt
version: Tiny # Tiny, Base, Small, Large, XLarge
name: ${model.architecture}${model.version}
freeze_base: true
finetune_whole_model: true
preprocessing: null
target_size:
  - 200
  - 200
instantiate:
  _target_: tensorflow.keras.applications.${model.architecture}${model.version}
  include_top: false
  weights: imagenet
  input_shape:
    - 200
    - 200
    - 3
  pooling: avg
