architecture: ConvNeXt
version: Tiny # Tiny, Base, Small, Large, XLarge
name: ${model.architecture}${model.version}
freeze_base: true
finetune_whole_model: true
preprocessing: null
instantiate:
  _target_: tensorflow.keras.applications.${model.architecture}${model.version}
  include_top: false
  weights: imagenet
  input_shape:
    - ${train.target_size[0]}
    - ${train.target_size[1]}
    - ${dataset.channels}
  pooling: avg
