architecture: SeparableConvCNN
version: v1
name: ${model.architecture}${model.version}
freeze_base: false
finetune_base: false
num_finetune_layers: 0
preprocessing:
  _target_: src.custom_models.baseline_cnn.preprocess_input
  _partial_: true
instantiate:
  _target_: src.custom_models.custom_cnn.get_base_model
  input_shape:
    - ${train.target_size[0]}
    - ${train.target_size[1]}
    - ${dataset.channels}
top_layer_architecture: null
