architecture: EfficientNetV2
version: B0 # version ranges from B0 to B3 and S, M and L
name: EfficientNetV2${model.version}
target_size:
  - 224
  - 224
instantiate:
  _target_: tensorflow.keras.applications.EfficientNetV2${model.version}
  include_top: false
  weights: imagenet
  input_shape:
    - 224
    - 224
    - 3
  pooling: avg
