architecture: EfficientNetV2
version: B0 # version ranges from B0 to B3 and S, M and L
name: EfficientNetV2${model.version}
freeze_base: true
finetune_base: true
num_finetune_layers: 40
preprocessing: null

# to pass to hydra.utils.instantiate
instantiate:
  _target_: tensorflow.keras.applications.EfficientNetV2${model.version}
  include_top: false
  weights: imagenet
  input_shape:
    - ${train.target_size[0]}
    - ${train.target_size[1]}
    - ${dataset.channels}
  pooling: null

top_layer_architecture:
  _target_: src.top_layer_architectures.resnet_top
  _partial_: true
