name: EfficientNetV2B0
target_size:
  - 224
  - 224
instantiate:
  _target_: tensorflow.keras.applications.EfficientNetV2B0
  include_top: false
  weights: imagenet
  input_shape:
    - 224
    - 224
    - 3
  pooling: avg
