architecture: ResNet
version: 50 # or 101, 152
name: ${model.architecture}${model.version}
freeze_base: true
finetune_base: true
num_finetune_layers: all
preprocessing:
  _target_: tensorflow.keras.applications.resnet.preprocess_input
  _partial_: true
instantiate:
  _target_: tensorflow.keras.applications.${model.architecture}${model.version}
  include_top: false
  weights: imagenet
  input_shape:
    - ${train.target_size[0]}
    - ${train.target_size[1]}
    - ${dataset.channels}
  pooling: null

top_layer_architecture:
  _target_: src.top_layer_architectures.resnet_top
  _partial_: true
