architecture: ResNet
version: 50 # or 101, 152
name: ResNet${model.version}
finetune_whole_model: true
preprocessing:
  _target_: tensorflow.keras.applications.resnet.preprocess_input
  _partial_: true
target_size:
  - 200
  - 200
instantiate:
  _target_: tensorflow.keras.applications.ResNet${model.version}
  include_top: false
  weights: imagenet
  input_shape:
    - 200
    - 200
    - 3
  pooling: avg
