architecture: VGG
version: 16 # or 19
name: ${model.architecture}${model.version}
freeze_base: true
finetune_base: true
num_finetune_layers: 11
preprocessing:
  _target_: tensorflow.keras.applications.vgg${model.version}.preprocess_input
  _partial_: true
instantiate:
  _target_: tensorflow.keras.applications.${model.architecture}${model.version}
  include_top: false
  weights: imagenet
  input_shape:
    - ${train.target_size[0]}
    - ${train.target_size[1]}
    - ${dataset.channels}
  pooling: null

top_layer_architecture:
  _target_: src.top_layer_architectures.fully_connected_with_dropout
  _partial_: true
