architecture: VGGFace
version: null
name: ${model.architecture}
freeze_base: true
finetune_base: true
num_finetune_layers: 7
preprocessing:
  _target_: tensorflow.keras.applications.vgg16.preprocess_input
  _partial_: true
instantiate:
  _target_: src.custom_models.vggface.get_base_model
  input_shape:
    - ${train.target_size[0]}
    - ${train.target_size[1]}
    - ${dataset.channels}
top_layer_architecture:
  _target_: src.top_layer_architectures.resnet_top
  _partial_: true
