defaults:
  - model: efficientnetv2-b0
  - dataset: utkface
  - optimizer: adam
  - _self_

wandb:
  project: UTKFace-Age-prediction
  group: null
  name: null
  mode: disabled # or online
  key: ${oc.env:WANDB_API_KEY}
  id: null
  resume: allow
  tags: null
  notes: null
  sync_tensorboard: false

# first round of fine tuning (only the last layers)
lr_schedule:
  _target_: tensorflow.keras.optimizers.schedules.ExponentialDecay
  initial_learning_rate: 1e-3
  decay_steps: 100_000
  decay_rate: 0.96

# when finetuning the whole (pretrained) model
lr_schedule_finetuning:
  _target_: tensorflow.keras.optimizers.schedules.ExponentialDecay
  initial_learning_rate: 1e-5
  decay_steps: 100_000
  decay_rate: 0.99

data_dir: data/
log_dir: logs/
model_dir: models/
