defaults:
  - _self_

wandb:
  project: UTKFace-Age-prediction
  group: null
  name: null
  mode: online # deprecated
  key: ${oc.env:WANDB_API_KEY}

data_dir: data/
log_dir: logs/
model_dir: models/
