defaults:
  - model: efficientnetv2b0
  - dataset: utkface
  - optimizer: adam
  - lr_schedule: exponential_decay
  - _self_

finetune_whole_model: false # applies to pretrained models only

train:
  task: regression
  loss: mean_absolute_error
  metrics:
    - mae
  epochs: 150
  batch_size: 32

augment:
  active: true
  factors:
    random_rotation: 0.2
    random_translation: 0.1
    random_brightness: 0.1
    random_flip: horizontal

wandb:
  project: test
  group: null
  name: null
  mode: offline # or online
  id: null
  resume: allow
  tags: null
  notes: null
  sync_tensorboard: false

callbacks:
    early_stopping_patience: 5
    monitor: val_mae
    use_wandb: true
    model_ckpt: true
    ckpt_filepath: ${ckpt_dir}/model-{epoch:02d}-{val_mae:.2f}
    visualize_predictions: true
    with_wandb_ckpt: false

data_dir: data
log_dir: logs
model_dir: models
ckpt_dir: ckpts
