defaults:
  - model: efficientnetv2
  - dataset: utkface
  - optimizer: adam
  - lr_schedule: exponential_decay
  - _self_

train:
  task: regression
  loss: mean_squared_error
  metrics:
    - mae
  epochs: 150
  batch_size: 32
  seed: 0
  target_size:
    - 64
    - 64
  cache_dataset: true
  cv_folds: 1

augment:
  active: true
  factors:
    random_rotation: 0.1
    random_translation: 0.1
    random_brightness: null
    random_flip: horizontal

wandb:
  project: UTKFace-Age-Regression
  group: ${model.architecture}
  name: null
  mode: online # or offline
  id: null
  resume: allow
  tags:
    - ${model.name}
  notes: null
  sync_tensorboard: false

callbacks:
    early_stopping_patience: 5
    monitor: val_mae
    use_wandb: true
    model_ckpt: false
    ckpt_filepath: ${ckpt_dir}/model-{epoch:02d}-{val_mae:.2f}
    visualize_predictions: false
    with_wandb_ckpt: false

data_dir: data
log_dir: logs
model_dir: models
ckpt_dir: ckpts
