#
name: Tests
on:
  push:
    branches-ignore:
      - main # Ignore main branch, deploy workflow will call it
  pull_request:
  workflow_call:

jobs:
  test:
    name: Run Tests on Python ${{ matrix.python-version }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Cache conda
      #   uses: actions/cache@v3
      #   env:
      #     # Increase this value to reset cache if etc/example-environment.yml has not changed
      #     CACHE_NUMBER: 0
      #   with:
      #     path: ~/conda_pkgs_dir
      #     key:
      #       ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
      #       hashFiles('etc/example-environment.yml') }}

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: age-prediction
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          use-only-tar-bz2: true

      - run: |
          conda info
          conda list

      - name: poetry info
        run: poetry env info

      - name: Install packages
        run: |
          conda activate age-prediction
          poetry install

      - name: Run tests
        run: |
          conda activate age-prediction
          poetry run pytest
