#
name: Tests
on:
  push:
    branches-ignore:
      - main # Ignore main branch, deploy workflow will call it
  pull_request:
  workflow_call:

jobs:
  test:
    name: Run Tests on Python ${{ matrix.python-version }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: age-prediction
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: show poetry env info
        run: poetry env info

      - name: Install packages
        run: poetry install

      - name: Run tests
        run: poetry run pytest
